services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: 'revision'
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
      ETCD_SNAPSHOT_COUNT: 50000
    volumes:
      - ./volumes/milvus/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./volumes/milvus/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    image: milvusdb/milvus:v2.5.0-beta
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    # ports:
    #   - 8080:19530
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MILVUS_USER: ${MILVUS_USER:-admin}
      MILVUS_PASSWORD: ${MILVUS_PASSWORD:-123456}
      MILVUS_AUTHORIZATION_ENABLED: true
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    depends_on:
      - etcd
      - minio

  mysql:
    image: mysql:8.4
    container_name: mysql-standalone
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vanna}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: --max-connections=100

  vanna-flask-app:
    build: .
    image: vanna-flask-app
    container_name: vanna-flask-app
    restart: always
    environment:
      OPENAI_LLM_MODEL: ${OPENAI_LLM_MODEL}
      OPENAI_LLM_API_KEY: ${OPENAI_LLM_API_KEY:-sk-}
      OPENAI_LLM_BASE_URL: ${OPENAI_LLM_BASE_URL}
      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL}
      OPENAI_EMBEDDING_API_KEY: ${OPENAI_EMBEDDING_API_KEY:-sk-}
      OPENAI_EMBEDDING_BASE_URL: ${OPENAI_EMBEDDING_BASE_URL}
      MILVUS_URI: ${MILVUS_URI:-milvus:19530}
      MILVUS_USER: ${MILVUS_USER:-admin}
      MILVUS_PASSWORD: ${MILVUS_PASSWORD:-123456}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_DBNAME: ${MYSQL_DBNAME:-vanna}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
    command: python main.py
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - milvus